language: java

jdk:
  - oraclejdk8
  - oraclejdk7

before_install:
  - pip install --user codecov

script: mvn clean install

after_success:
  - codecov

notifications:
  email:
    on_failure: change
